version: '3.8'
services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
    restart: unless-stopped
  
  grafana:
    image: grafana/grafana:9.0.0
    ports:
      - '3000:3000'
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboard:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: unless-stopped

  alertmanager:
    image: prom/alertmanager:latest
    ports:
      - '9093:9093'
    # volumes:
    #   - ./promentheus/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:latest
    network_mode: host
    restart: unless-stopped