version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: streamsphere-mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  minio:
    image: minio/minio
    container_name: streamsphere-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  redis:
    image: redis:7
    container_name: stremesphere-redis
    ports:
      - "6379:6379"

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    environment:
      - node.name=es01
      - cluster.name=es-docker
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - '9200:9200'

volumes:
  mongo_data:
  minio_data:
